### ISSUE TITLE
ADD ME IN CONTRIBUTOR 

### ISSUE THREAD

**Issue by neeraj395** [DisWeb-site/DisWeb#39]
@PuneetGopinath 

- [x] ADD ME AS A CONTRIBUTOR

**Comment by neeraj395** [comment]
But I can't update any file its showing you need to fork this 🤔 

@PuneetGopinath

**Comment by neeraj395** [comment]
Now you added nice

**Comment by PuneetGopinath** [comment]
> Now you added nice

No not now
